#!/bin/bash

while true; do
    # Run AT+CGMM to get the modem model
    echo -en "AT+CGMM\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/modemmodel.txt
    sleep 2

    # Run AT+GMR to get the modem version
    echo -en "AT+GMR\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/modemversion.txt
    sleep 2

    # Run AT+EGMR to get the modem imei
    echo -en "AT+EGMR=0,7\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/modemimei.txt
    sleep 2

    # Run AT+GMR to get the modem iccid
    echo -en "AT+ICCID\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/modemiccid.txt
    sleep 2

    # Run AT+COPS？ to get the cops
    echo -en "AT+COPS?\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/cops.txt
    sleep 2

    #  Run AT+CGCONTRDP once then proceed to while loop
    echo -en "AT+CGCONTRDP=1\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/apn.txt
    sleep 2

    # Run AT+QUIMSLOT? to get the current sim slot
    echo -en "AT+QUIMSLOT?\r\n" | microcom -t 1000 /dev/ttyOUT > /tmp/simslot.txt
    sleep 2

    # Send request to modem and wait 3 seconds for data
    echo -en "AT+QSPN;+CEREG=2;+CEREG?;+CEREG=0;+C5GREG=2;+C5GREG?;+C5GREG=0;+CSQ;+QENG=\"servingcell\";+QRSRP;+QCAINFO;+QNWPREFCFG=\"mode_pref\";+QTEMP\r\n" \
    | microcom -t 3000 /dev/ttyOUT > /tmp/modemstatus.txt
    if [ $? -eq 0 ]
    then
        # Parse
        if [ -f /tmp/modemstatus.txt ]
        then
    	      /usrdata/simpleadmin/scripts/modemstatus_parse.sh
        fi
    fi
    sleep 25  # Add a sleep to avoid CPU overload
done